version: '3'
services: 
    app:
        container_name: bn-frontend
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9001"        
        volumes: 
            - ./:/app
            - /app/node_modules
